#2
>>> dna_2="ACTGATCGATTACGTATAGTAGAATTCTATCATACATATATATCGATGCGTTCAT"
>>> print(dna_2.replace("A", "W"))
#WCTGWTCGWTTWCGTWTWGTWGWWTTCTWTCWTWCWTWTWTWTCGWTGCGTTCWT
>>> dna_2a="WCTGWTCGWTTWCGTWTWGTWGWWTTCTWTCWTWCWTWTWTWTCGWTGCGTTCWT"
>>> print(dna_2a.replace("T", "A"))
#WCAGWACGWAAWCGAWAWGAWGWWAACAWACWAWCWAWAWAWACGWAGCGAACWA
>>> dna_2b="WCAGWACGWAAWCGAWAWGAWGWWAACAWACWAWCWAWAWAWACGWAGCGAACWA"
>>> print(dna_2b.replace("W", "T"))
#TCAGTACGTAATCGATATGATGTTAACATACTATCTATATATACGTAGCGAACTA
>>> dna_2c="TCAGTACGTAATCGATATGATGTTAACATACTATCTATATATACGTAGCGAACTA"
>>> print(dna_2c.replace("C", "X"))
#TXAGTAXGTAATXGATATGATGTTAAXATAXTATXTATATATAXGTAGXGAAXTA
>>> dna_2d="TXAGTAXGTAATXGATATGATGTTAAXATAXTATXTATATATAXGTAGXGAAXTA"
>>> print(dna_2d.replace("G", "C"))
#TXACTAXCTAATXCATATCATCTTAAXATAXTATXTATATATAXCTACXCAAXTA
>>> dna_2e="TXACTAXCTAATXCATATCATCTTAAXATAXTATXTATATATAXCTACXCAAXTA"
>>> print(dna_2e.replace("X", "G"))
#TGACTAGCTAATGCATATCATCTTAAGATAGTATGTATATATAGCTACGCAAGTA

