#1
>>> dna_1= "ACTGATCGATTACGTATAGTATTTGCTATCATACATATATATCGATGCGTTCAT"
>>> print(dna_1)
ACTGATCGATTACGTATAGTATTTGCTATCATACATATATATCGATGCGTTCAT
>>> AT_count=dna_1.count('AT')
>>> print("AT: " +str(AT_count))
AT: 12
