#4
>>> dna_4= "ATCGATCGATCGATCGACTGACTAGTCATAGCTATGCATGTAGCTACTCGATCGATCGATCGATCGATCGATCGATCGATCGATCATGCTATCATCGATCGATATCGATGCATCGACTACTAT"
>>> print(dna_4[0:63])
#ATCGATCGATCGATCGACTGACTAGTCATAGCTATGCATGTAGCTACTCGATCGATCGATCGA
>>> dna_4a="ATCGATCGATCGATCGACTGACTAGTCATAGCTATGCATGTAGCTACTCGATCGATCGATCGA"
>>> print(dna_4[91:200])
#TCATCGATCGATATCGATGCATCGACTACTAT
>>> dna_4b="TCATCGATCGATATCGATGCATCGACTACTAT"
>>> print(dna_4[64:91])
CGATCGATCGATCGATCGATCATGCTA
>>> dna_4coding="CGATCGATCGATCGATCGATCATGCTA"
>>> dna_4al= len(dna_4a)
>>> print(str(dna_4al))
#63
>>> dna_4bl= len(dna_4b)
>>> print(str(dna_4bl))
#32
>>> dna_4codingl= len(dna_4coding)
>>> print(str(dna_4codingl))
#27
>>> dna_4l= len(dna_4)
>>> print(str(dna_4l))
#122
#27/122
